name: Run test cases automatically

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18

      - name: Test
        env:
          APP_ID: '${{ secrets.FEISHU_APP_ID }}'
          APP_SECRET: '${{ secrets.FEISHU_APP_SECRET }}'
        run: go test -v ./...